name: 'Cleanup Disk'
description: 'Delete pre-installed sofeware in github action.'
author: 'HandsomeYingyan'
branding:
  icon: 'trash-2'
  color: 'gray-dark'
inputs:
  retain:
    description: Retain some packages.
    required: false
    default: 'python,linux'

runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        echo "-------------Disk info before cleanup----------------"
        df -h
        echo "-----------------------------------------------------"

    - name: delete go
      shell: bash
      run: |
        if [[ "${{ inputs.retain }}" == *"go"* ]]; then
          echo "ignore go"
        else
          echo "delete go"
          echo "       default"
          sudo rm -rf /opt/hostedtoolcache/go
        fi

    - name: delete ruby
      shell: bash
      run: |
        if [[ "${{ inputs.retain }}" == *"ruby"* ]]; then
          echo "ignore ruby"
        else
          echo "delete ruby"
          sudo rm -rf /opt/hostedtoolcache/Ruby
        fi

    - name: delete pypy
      shell: bash
      run: |
        if [[ "${{ inputs.retain }}" == *"pypy"* ]]; then
          echo "ignore pypy"
        else
          echo "delete pypy"
          sudo rm -rf /opt/hostedtoolcache/PyPy
        fi

    - name: delete CodeQL
      shell: bash
      run: |
        if [[ "${{ inputs.retain }}" == *"codeql"* ]]; then
          echo "ignore codeql"
        else
          echo "delete codeql"
          sudo rm -rf /opt/hostedtoolcache/CodeQL
        fi
 
    - name: delete node
      shell: bash
      run: |
        if [[ "${{ inputs.retain }}" == *"node"* ]]; then
          echo "ignore node"
        else
          echo "delete node"
          echo "       default"
          sudo rm -rf /usr/local/lib/node_modules
          sudo rm -rf /opt/hostedtoolcache/node
        fi

    - name: delete dotnet
      shell: bash
      run: |
        if [[ "${{ inputs.retain }}" == *"dotnet"* ]]; then
          echo "ignore dotnet"
        else
          echo "delete dotnet"
          echo "       default"
          sudo rm -rf /usr/share/dotnet
        fi

    - name: delete swift
      shell: bash
      run: |
        if [[ "${{ inputs.retain }}" == *"swift"* ]]; then
          echo "ignore swift"
        else
          echo "delete swift"
          echo "       default"
          sudo rm -rf /usr/share/swift
        fi

    - name: delete rust
      shell: bash
      run: |
        if [[ "${{ inputs.retain }}" == *"rust"* ]]; then
          echo "ignore rust"
        else
          echo "delete rust"
          echo "       default"
          sudo rm -rf /usr/share/rust
        fi

    - name: delete miniconda
      shell: bash
      run: |
        if [[ "${{ inputs.retain }}" == *"miniconda"* ]]; then
          echo "ignore miniconda"
        else
          echo "delete miniconda"
          echo "       default"
          sudo rm -rf /usr/share/miniconda
        fi

    - name: delete gradle
      shell: bash
      run: |
        if [[ "${{ inputs.retain }}" == *"gradle"* ]]; then
          echo "ignore gradle"
        else
          echo "delete gradle"
          sudo rm -rf /usr/share/gradle-*
        fi

    - name: delete az
      shell: bash
      run: |
        if [[ "${{ inputs.retain }}" == *"az"* ]]; then
          echo "ignore az"
        else
          echo "delete az"
          echo "       default"
          sudo rm -rf /opt/az
          sudo rm -rf /usr/share/az_*
        fi

    - name: delete android
      shell: bash
      run: |
        if [[ "${{ inputs.retain }}" == *"android"* ]]; then
          echo "ignore android"
        else
          echo "delete android"
          echo "       default"
          sudo rm -rf /usr/local/lib/android
        fi

    - name: delete python
      shell: bash
      run: |
        if [[ "${{ inputs.retain }}" == *"python"* ]]; then
          echo "ignore python"
        else
          echo "delete python"
          echo "       sys-2.X"
          sudo rm -rf /usr/local/lib/python2*
          echo "       sys-3.X"
          sudo rm -rf /usr/local/lib/python3*
          sudo rm -rf /opt/hostedtoolcache/Python
        fi

    - name: delete julia
      shell: bash
      run: |
        if [[ "${{ inputs.retain }}" == *"julia"* ]]; then
          echo "ignore julia"
        else
          echo "delete julia"
          sudo rm -rf /usr/local/julia*
        fi

    - name: delete vcpkg
      shell: bash
      run: |
        if [[ "${{ inputs.retain }}" == *"vcpkg"* ]]; then
          echo "ignore vcpkg"
        else
          echo "delete vcpkg"
          echo "       default"
          sudo rm -rf /usr/local/share/vcpkg
        fi

    - name: delete jvm
      shell: bash
      run: |
        if [[ "${{ inputs.retain }}" == *"jvm"* ]]; then
          echo "ignore jvm"
        else
          echo "delete jvm"
          echo "       default"
          sudo rm -rf /usr/lib/jvm
        fi

    - name: delete java adopt sdk
      shell: bash
      run: |
        if [[ "${{ inputs.retain }}" == *"jdk"* ]]; then
          echo "ignore jdk"
        else
          echo "delete jdk"
          echo "       default"
          sudo rm -rf /opt/hostedtoolcache/Java_Adopt_jdk
        fi

    - name: delete mono
      shell: bash
      run: |
        if [[ "${{ inputs.retain }}" == *"mono"* ]]; then
          echo "ignore mono"
        else
          echo "delete mono"
          echo "       default"
          sudo rm -rf /usr/lib/mono
        fi

    - name: delete llvm
      shell: bash
      run: |
        if [[ "${{ inputs.retain }}" == *"llvm"* ]]; then
          echo "ignore llvm"
        else
          echo "delete llvm"
          sudo rm -rf /usr/lib/llvm-*
          sudo rm -rf /usr/include/llvm-*
        fi

    - name: delete firefox
      shell: bash
      run: |
        if [[ "${{ inputs.retain }}" == *"firefox"* ]]; then
          echo "ignore firefox"
        else
          echo "delete firefox"
          echo "       default"
          sudo rm -rf /usr/lib/firefox
        fi

    - name: delete R
      shell: bash
      run: |
        if [[ "${{ inputs.retain }}" == *"r"* ]]; then
          echo "ignore r"
        else
          echo "delete r"
          echo "       default"
          sudo rm -rf /usr/lib/R
        fi

    - name: delete Linux Headers
      shell: bash
      run: |
        if [[ "${{ inputs.retain }}" == *"linux"* ]]; then
          echo "ignore linux headers"
        else
          echo "delete linux headers"
          echo "       default"
          sudo rm -rf /usr/src/linux-*
        fi

    - name: delete google-cloud-sdk
      shell: bash
      run: |
        if [[ "${{ inputs.retain }}" == *"google-cloud-sdk"* ]]; then
          echo "ignore google-cloud-sdk"
        else
          echo "delete google-cloud-sdk"
          echo "       default"
          sudo rm -rf /usr/lib/google-cloud-sdk
        fi

    - name: delete php
      shell: bash
      run: |
        if [[ "${{ inputs.retain }}" == *"php"* ]]; then
          echo "ignore php"
        else
          echo "delete php"
          echo "       default"
          sudo rm -rf /usr/include/php
        fi

    - name: delete ghc
      shell: bash
      run: |
        if [[ "${{ inputs.retain }}" == *"ghc"* ]]; then
          echo "ignore ghc"
        else
          echo "delete ghc"
          sudo rm -rf /opt/ghc
        fi

    - name: delete linuxbrew
      shell: bash
      run: |
        if [[ "${{ inputs.retain }}" == *"linuxbrew"* ]]; then
          echo "ignore linuxbrew"
        else
          echo "delete linuxbrew"
          echo "       default"
          sudo rm -rf /home/linuxbrew
        fi


    - shell: bash
      run: |
        echo "-------------Disk info after cleanup----------------"
        df -h
        echo "-----------------------------------------------------"
