name: 'Cleanup Disk'
description: 'Delete pre-installed sofeware in github action.'
author: 'curoky'
branding:
  icon: 'trash-2'
  color: 'gray-dark'
inputs:
  retain:
    description: retain some packages.
    required: false
    default: ''
  show_stat:
    description: show cleanup stat
    required: false
    default: "true"

runs:
  using: 'composite'
  steps:
    - name: install dependency
      shell: bash
      run: |
        sudo apt-get install python3-setuptools
        python3 -m pip install --user -r ${{ github.action_path }}/requirements.txt

    - name: stat info
      shell: bash
      run: >
        python3 ${{ github.action_path }}/src/meta-info.py --clean=1
        --meta_path=${{ github.action_path }}/src/meta/ubuntu-meta.json
        --result_path=${{ github.action_path }}/ubuntu-meta.txt
        --retain_list=${{ inputs.retain }}
        --show_stat=${{ inputs.show_stat }}

    - name: cleanup disk
      shell: bash
      run: grep -Po "\[[\w/]*\]" ${{ github.action_path }}/ubuntu-meta.txt | sed 's/\[//g;s/\]//g' | xargs sudo rm -rf --
