name: 'Cleanup Disk'
description: 'Delete pre-installed sofeware in github action.'
author: 'curoky'
branding:
  icon: 'trash-2'
  color: 'gray-dark'
inputs:
  retain:
    description: Retain some packages.
    required: false
    default: 'python,node'
  count_deleted_size:
    description: Calculate the size of the cleanup.
    required: false
    default: 'false'
  verbose:
    description: Show additional details.
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: install dependency
      shell: bash
      run: |
        sudo python3 -m pip install -r ${{ github.action_path }}/requirements.txt

    - name: stat info
      shell: bash
      run: >
        sudo ${{ github.action_path }}/src/meta-info.py
        --dry_run=0 --count_deleted_size=1
        --retain=${{ inputs.retain }}
