name: disk info

on:
  schedule:
    - cron: '0 0 * * 0'
  # push:

jobs:
  disk_info:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-10.15
          - macos-11.0
          - ubuntu-16.04
          - ubuntu-18.04
          - ubuntu-20.04

    runs-on: ${{ matrix.os }}
    steps:
      - name: install ncdu
        run: |
          wget https://dev.yorhel.nl/download/ncdu-1.15.1.tar.gz
          tar -xzvf ncdu-1.15.1.tar.gz && cd ncdu-1.15.1
          ./configure && make && sudo make install

      # - uses: curoky/actions/tmate@master

      - name: get disk info
        run: |
          df -h > df.txt
          ncdu --exclude "/System/Volumes" -o ncdu.json /

      - name: upload disk info
        uses: actions/upload-artifact@v2
        with:
          name: diskInfo
          path: |
            df.txt
            ncdu.json
