name: meta info

on:
  schedule:
    - cron: '0 0 * * 0'
  # push:

jobs:
  meta_info:
    strategy:
      matrix:
        os:
          - ubuntu-18.04
          - ubuntu-20.04
          - ubuntu-latest

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: install dependency
        run: |
          sudo apt-get install python3-setuptools
          python3 -m pip install --user -r requirements.txt

      - name: meta info
        run: >
          python3 src/meta-info.py
          --meta_path=src/meta/ubuntu-meta.json
          --result_path=${{ matrix.os }}-meta.txt

      - name: upload meta info
        uses: actions/upload-artifact@v2
        with:
          name: metaInfo
          path: ${{ matrix.os }}-meta.txt
